name: build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        ocaml-compiler:
          - "ocaml-variants.4.14.1+mingw64c"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.ignorecase false

      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3.0.0-beta
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          allow-prerelease-opam: true

      - run: opam install . --with-test --deps-only

      - run: opam exec -- make test